site_name: podStation
repo_url: https://github.com/podStation/podStation
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  features:
  - navigation.tabs
  - content.action.edit
  palette:
    primary: black
    accent: teal
  icon: 
    logo: fontawesome/solid/rss
  favicon: images/favicon.ico
plugins:
  - blog
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@podstation
      name: podStation on Mastodon @ fosstodon.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/podStation_app
      name: podStation on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/podStation
      name: podStation on Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/podStation
      name: podStation org on GitHub
extra_javascript:
- javascripts/handlebars-4.7.6.min.js
- javascripts/jquery-3.5.1.min.js
- javascripts/subscribeInPodstation.js
nav:
- Home: index.md
- blog/index.md
- contacts.md
- Contribute: https://github.com/podStation/.github/blob/master/CONTRIBUTING.md
- Support: https://github.com/podStation/podStation#support-and-contact
- supportus.md 