authors:
  dellagustin:
    name: Guilherme Dellagustin
    description: Author and maintainer of podStation
    avatar: https://avatars.githubusercontent.com/u/260113?v=4
    slug: dellagustin           # Author profile slug
    url: https://dellagustin.github.io